### ISSUE TITLE
Candidate: MajesticBank for MAGIC Monero Fund

### ISSUE THREAD

**Issue by MajesticBank** [MAGICGrants/Monero-Fund-Elections#1]
- [x ] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [x ] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [x ] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [x ] I understand that an active committee is the number one factor in a Fund's success.
- [x ] I am at least 18 years old.

I have a feeling that Magic Fund is step into right direction and with time and growth it could become probably biggest development fund not just around Monero but around many cryptocurrencies in couple years from now. We definitely need more support for developers and open-source technologies specially in the sphere of privacy which somehow still hadn't received mainstream adoption and coverage.

For me best thing to have is to have ability to give to others and empower other people and let them reach their full potential. Raising funds and motivate other people to donate is something I do with pleasure. Often using out-of-ordinary ways to reach funding goals is not something new to me. Information and small prints are very important for me so Fund would benefit for most up-to-date data on almost all cryptocurrency and privacy topics from my side.

If I am elected as Committee member, I will to my best knowledge and in best faith serve interest of the Fund and follow it's decisions.
Probably main reasons for my application is because I feel my presence would help the Fund in many aspects and out of respect for Vik.

Thanks for your attention.

**Comment by SamsungGalaxyPlayer** [comment]
Thank you for announcing your candidacy!
