### ISSUE TITLE
Candidate: Kewbit for MAGIC Monero Fund

### ISSUE THREAD

**Issue by KewbitXMR** [MAGICGrants/Monero-Fund-Elections#10]
- [✔️] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [✔️] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [✔️] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [✔️] I understand that an active committee is the number one factor in a Fund's success.
- [✔️] I am at least 18 years old.

Replace this and the below text with approximately 5 paragraphs explaining:
* Why you are running for the committee
* I think it's important to try to tackle some of the top echelon corruption of community members, and make sure that anyone who is being funded is treated fairly and with respect by other members, I would like to make changes that favor the one being funded slightly more and re-imagine the fund CCS rules, if they are not already different from the ones on the Monero CCS rules page.
* Why you are a good candidate
* I am fair when, I will treat you with respect if you treat myself and others with respect, I notice nuances that others may skip in peoples character, intent and general good faith.
* What experience you bring to the table (eg: fundraising)
* I am technologically very knowledgeable, I am able to report on the integrity of others based on their nuanced actions and what they are able to produce, even with little information about them, I have a clear vision of how to appropriate funds efficiently so they are not wasted, I practice this every day, as a domain broker, I builder up value from firstly, recognizing the value, being example to bring out more value in people with key motivation tactics which I find to be specific to that individuals desires. I can help people grow and feel comfortable in the work they are doing even if they are new, I'm encouraging and positive - apart from when not treated with positivity (a weaknesss) I can strategize plans of action in detail successfully and consistently.
* What you hope the Fund will accomplish while you are on the committee
* I would hope to both seek, and evaluate sufficient talent for purposes specific to growing the Monero community, I would use connections as a tool to help market Monero in a positive way. I want to switch the light on, so that Monero is not seen as a Darknet asset, and seen as something valid and accepted by governments and investors, I recognize this is a challenge but with the right kind of people in the community, you can build anytthing, change anything. Part of my plan would be to recognize the abusers of the system and their reputation and how it's used, if it's positive or negative. I would advise on where I believe corruption would take place impartially. I would not take pay for this role.
* Contact information (optional)
* me@kewbit.org
* 
Make sure to submit your application before the due date, and please campaign ethically in the community! Good luck, and thanks for applying!

**Comment by SyntheticBird45** [comment]
Imagine buying 20 bots and thinking you can fool someone

**Comment by privacyOG** [comment]
You cant be serious after everything thats happened. If your genuine coder go quitely finish off the haveno app, release it as FOSS including all source code and you might be able to repair your credibilty. You did all this to yourself. Please dont reply back!

**Comment by SamsungGalaxyPlayer** [comment]
@KewbitXMR your committee candidacy has been disqualified because your recent blog post advertises an alternative "Monero Fund" at a different domain, which appears to be an attempt to impersonate the MAGIC Monero Fund. This and several other of your actions casts significant doubt at your intentions. The MAGIC Grants board has voted unanimously to declare you ineligible for this committee position. You will be eligible to run again next year if these issues are resolved.

**Comment by KewbitXMR** [comment]
> @KewbitXMR your committee candidacy has been disqualified because your recent blog post advertises an alternative "Monero Fund" at a different domain, which appears to be an attempt to impersonate the MAGIC Monero Fund. This and several other of your actions casts significant doubt at your intentions. The MAGIC Grants board has voted unanimously to declare you ineligible for this committee position. You will be eligible to run again next year if these issues are resolved.

**It's great that spotted but a shame you jumped the gun on disqualifying** (noting the 'community sentiment' coming from again those top 9 people mentioned 9 monero echelons.)

I can explain what monero.fund is and will be however, not directly associated with myself it will in-fact be laid out in a 501(c)3 USD based charitable corporation, I may or may not be on the board of that. The purpose of this is to give people a reputation based proof-of-history and proof-of-contribution based vote, as apposed to proof of popularity, which is very generic and not fit for purpose here (you wont be able to just introduce people out the blue very easily with it's abuse-resistant philosophy, which I'm sure once in BETA the community at large will feel much more empowered by with their votes and the system in general), those those of you who reacted positivity to the post, it's good new because we're going ahead with that whether or not MagicGrant think they need me in their roster. I am building this under the purview of another funder who's directly who's spent a considerable amount donating to Monero CSS and Bounties only to be disappointed by the way they are handled, on several occasions, not once or twice.

The http://monero.fund/ will run on peervote.org which is the software I will be developing for it. Though I would have brought some integrity to this it's clear that, this is not the primary directive, and if you are threatened by decentralising the value you are adding I get it, but this further builds up a case against Monero and it's corruption and misappropriation of funds, evidently to show anti-support on such system.

If there were not aware if it's intentions then either way, you could have asked before disqualifying, it's always interesting to see how deep this rabbit hole goes and seeing the same faces along the road :)

**Comment by KewbitXMR** [comment]
It's a shame, also that I don't get to reveal my identity, something I've been excited to do for some time.

**Comment by SamsungGalaxyPlayer** [comment]
MAGIC Grants has its own open-source campaign website live at https://donate.magicgrants.org

The code is available here: https://github.com/MAGICGrants/campaign-site/
