### ISSUE TITLE
Candidate: [artlimber] for MAGIC Monero Fund

### ISSUE THREAD

**Issue by artlimber** [MAGICGrants/Monero-Fund-Elections#2]
- [X] I have read and understand the [MAGIC Monero Fund documents](https://magicgrants.org/funds/monero/).
- [X] I have read and understand the relevant [MAGIC Grants policies](https://magicgrants.org/about/documentation/).
- [X] I understand that should I be in a position to receive funds from MAGIC Grants for any reason, I will need to provide identifying information to the organization privately. Election to a committee does not guarantee compensation even if compensation is made available, since MAGIC Grants has legal limitations on how it can disburse funds.
- [X] I understand that an active committee is the number one factor in a Fund's success.
- [X] I am at least 18 years old.

I have been following the work done by the MAGIC Fund since the last committee election and am impressed with what has been accomplished. I want to help continue this trend as I strongly believe privacy is a human right and that Monero represents the best effort to-date for truly private, fungible, permission-less digital money.

As a committee member I will be open to points of view that I don't agree with, be willing to compromise and always work towards utilitarian solutions that do the most good for the largest number of people. 

Using my knowledge and experience within cryptocurrency and open source communities I am confident in identifying worthy funding proposals. As a cryptocurrency educator, consultant, author and expert witness I've seen a thing or two and enjoy using my background to champion projects and proposals I feel a connection with.

_I cheekily hope that we finally decide to fund a globally affordable Monero-only hardware wallet! (jk but shoutout Csill Brimer:)_
In all seriousness I do hope that the fund continues to support similar initiatives to what they've already funded, namely ETH<>XMR swaps and the security audit for XMR ring signatures. I am aligned with all 5 statements in the fund's "Vision and Goals" and hope that we can grow the footprint of the MAGIC Fund with a combination of identifying valuable proposals and securing additional donations to fund them.

Thank you for the consideration, I can be reached via artlimber@protonmail.com
~Art L.

**Comment by SamsungGalaxyPlayer** [comment]
Thank you for announcing your candidacy!
